using System;
using System.Windows.Forms;

namespace WindowsFormsApplication1
{
    /// <summary>
    /// ch:P2 版本信息窗口：显示当前软件版本、发布日期与版本时间线。
    /// 版本号 = 推送仓库时打标签的版本（语义化 主.次.修订 + 发布日期），非随机字符串。
    /// </summary>
    public partial class FormVersion : Form
    {
        // 当前版本（与推送仓库的 git tag 一一对应）：语义化版本 + 发布日期
        public const string AppVersion = "1.3.21";
        public const string AppVersionDate = "2026-09-24";
        public const string AppRepoName = "正泰 VP八相机连续海康（M4 - 加密）";

        // 版本时间线：与仓库 git tag 一一对应（新版本在最前）
        private static readonly string[] VersionTimeline = new string[] 
        {
            "v1.3.21  2026-09-26  第26轮(现场定案：坏值属客户侧改写，通讯监控诊断日志默认关闭)：现场按第24轮判别流程实测确认——-32768/恒0 坏值产生在客户侧(PLC程序或第三方Modbus主站往1101写0x8000)，非我方链路问题，责任边界移交客户。支撑=第24轮日志三环铁证：环①原始串正确(测试值1,2,3,4)、环②全程唯一一条 addr=1100 vals=1/2/3/4 无重叠写且无任何写失败、环④读回1101在11:57:32/38=2(证明写入确实落进PLC)而后于4秒内被改-32768。取证完成，本轮关闭通讯监控诊断日志：①FormModbus Load 读 test.ini [camera] fankui_diag 默认由开(1)改为关(0)，判定同时由「非0即开」收紧为「仅显式=1才开」——键缺失/非法一律静默，现场 test.ini 不做任何改动即生效；②三环调用点(环①原始串、环②普通写/极速写 int/long/float/string 六分支、环④轮询读回)全部经 FankuiDiagLogByKey 统一把守，关闭态首行早返回=零锁零写开销；③代码与开关完整保留，复发取证时 test.ini [camera] fankui_diag=1 即重开(注意：若现场 test.ini 已显式存在 fankui_diag=1，需改为0或删该行)。R25 性能统计打印(chkPerfPrint 异常/心跳规则)不受本轮影响。构建0 error、单测20/20。",
            "v1.3.20  2026-09-26  第25轮(性能统计打印可开关+异常才打/心跳；现场PerfReport数据裁决挂起项)：现场回传连续[性能统计]窗口——收125~126帧/5s=25fps满帧、丢帧≈0(仅启动初期11/503=2.2%后归零)、回调1.1~3.3ms、检测13.6~19.4ms(25fps帧预算40ms余量足)、尾部0.0~0.3ms、占用3~8%(远低于80%告警线)。该数据为此前挂起的现场 PerfReport 依据，直接裁决：①抬高feng不需要(取流线程占用3~8%无瓶颈且满帧)——挂起项关闭；②12处Task.Run内联不做(尾部埋点0.0~0.3ms即内联收益上限，不值得改码)——挂起项关闭；③CreateLastRunRecord异步化无紧迫性(占用低位+检测余量足)——挂起项关闭；④历轮CPU/显示节拍优化未牺牲帧率实锤(满帧25fps+丢帧≈0)。本轮改码：①Form1 tabPage5 输出方式行右侧(390,351；numDisplayHz止于382、页宽581内无占用、AutoScroll可见)新增 WinForms 原生 chkPerfPrint CheckBox「性能统计打印」，沿用 R18 labelDisplayHz/numDisplayHz 手法=Designer 显式布局不写 resx、设计器可拖改。②打印规则改异常驱动：开关开=丢帧率≥1%(totalDrop*100>=totalGet)/任一路占用≥50%/任一路检测均耗时≥35ms 任一命中立即打整行并附[异常:丢帧率x%|占用>=50%|检测>=35ms]，否则每10分钟一条[心跳]；开关关=完全不打。计数器复位与窗口复位无条件执行(开关只管落盘、统计与既有≥80%[警告:采集瓶颈]不受影响)；日志量1.7万行/天→常态约150行/天。③ini code.ini camera/perf_print 默认1，Load 仿 display_hz 夹取回填(_perfPrintSyncing 防回写、CheckedChanged 落盘)；_perfPrintOn 为 volatile(汇总线程读)、_perfLastPrintMs 仅在 _perfReporting 单线程闩内读写。注：PERF_SELFTEST 埋点自检仍可用，但需开关处于开态。构建0 error、单测20/20。",
            "v1.3.19  2026-09-24  第24轮(读回显示假设排除+三环日志补全：环②补long/float/string+环④轮询读回)：现场实测环①②均正确(发出[1,0,3,4])而通讯页监控读回 1,-32768,3,4(pos1/3/4全对)，疑问「是否发送正确但轮询读显示坏值」。读码排除显示侧四证：①读写同源地址——xie/XieWuWriteOne 与 Fins_duxie 均取 fins_dic par.Value[1](FormModbus.cs:1624/1483)，不存在读错位；②字节学——ReadInt16 对 0x0000 任何字节序(ABCD/BADC/CDAB/DCBA)/符号转换恒为 0，-32768=0x8000 需线上存在 0x80 字节，而我们发出的字节集{00,01,00,00,00,03,00,04} 不含 0x80，任何排列/错位/截断拼不出；③失败与回显只写文本——读失败=「Read Failed」、写回显=「Write Success」(DemoUtils.cs:41/120)，SetModbusGridValue 透传无变换(1082)，网格里的数字只可能来自成功读回的寄存器原值；④客户独立 HSL Demo 双实现读到同值。结论：证据链闭合=我们发出正确+读回忠实 ⇒ 线上 1101 确为 0x8000，FC16 原子写(pos3/4 在随视觉输出更新即写入执行)后被改写，改写者三选一=我方重叠通道写(R23环②只插int为盲区，long/float位模式可含0x80)/PLC程序哨兵(0x8000像状态码)/第三方Modbus主站。本轮改码(FormModbus)三补：①环②补三分支——xie() long(值+32位HEX，JoinHex32)、float(值+原始位HEX，JoinHexF，BitConverter重解释)、string(截断后真正写入部分 string.Join range)；XieWuWriteOne long/float 同款补记(极速写为主用路径 xie_wu→XieWuWriteOne，原R23只插int分支=最大盲区)；②新增 FankuiDiagLogByKey(key,message) 同款限频(变化触发+每键10秒)，原 FankuiDiagLog 改为委托调用；Fins_duxie int 分支读回后记「反馈诊断 读回 addr=X val=V」(ReadInt16 结果暂存 rdR24，含读失败)，与环②同一日志时间轴夹击 0→0x8000 的翻转时刻；③开关沿用 test.ini [camera] fankui_diag(默认开，取证后置0)。现场判别升级：grep「解析」查 addr∈1100-1103 是否存在第二条写(有=我方重叠通道当场定位)；「读回」与「写解析」时间戳对齐看翻转点归属；仍乱=Wireshark 抓502(抓到非我方 FC06/FC16=第三方，抓不到而读回仍0x8000=PLC内部写)。构建0 error、单测20/20。",
            "v1.3.18  2026-09-24  第23轮(现场-32768/恒0问题：读码定界+反馈发送三环诊断日志)：现场反馈相机1第2位实际0收-32768(0x8000)、实际-1收-32767(0x8001)，两样本恰=0x8000−x；相机2第2,3位恒0；相机3,4全对；每相机反馈4寄存器、fmt全int；ToolBlock实拍输出为小数串「1,-0.4908,-0.1408,246.13」。读码定界：int写出链路(WriteCameraResult原样登记→Split(',')→(short)Math.Round(double.Parse)→FC16)为纯透传，全仓grep无32768/0x8000写入源；字节序仅影响32位配对且0x0000怎么交换仍是0；R21截断只砍尾部；同帧pos1/3/4正确反证CurrentCulture小数点为「.」解析正常(pos4 246.13→246/252在PLC读回正确)；由此小数串理论应发[1,0,0,246]、与PLC读回[1,-32768,-1,252]不符→坏值必在「我们实际发出的帧 / PLC程序或第二写入者」之间，我们换算环节不可能产生0x8000；相机2恒0另一高概率解释=±0.4类近零小数四舍五入到int恒0，属正常取整非缺陷，日志可直接证实。改码(FormModbus)：新增 FankuiDiagLog(cam,tag,text)——①WriteCameraResult记「原始串」(视觉ToolBlock输出原样)；②xie() int分支记「普通写解析 addr+vals」(真正进FC16的short[])；③XieWuWriteOne int分支记「极速写解析 addr+vals」(仅实际发起写时)；变化触发+每相机每类10秒节流防刷屏，ini camera/fankui_diag=0可关闭(默认开)。现场取证三步：跑一次取日志——原始串已错=视觉ToolBlock输出侧；原始串对而解析后错=我们换算(理论不可能，留证)；解析后对而PLC读回错=PLC程序或第二写入者(再配合Wireshark抓502端口FC16帧/我方配置窗读回网格对照)。仅落现场路modbustcp窗，Omron/RTU复现同款再移植。构建0 error、单测20/20。",
            "v1.3.17  2026-09-24  第22轮(第21轮三修复同族移植到欧姆龙/RTU配置窗+连接UI封送)：现场澄清未用 frm3 的 modbustcp、现场数据路是配置窗 modbus 族(FormModbus/FormOmron/FormModbusRtu)，故把 v1.3.16 落在 modbustcp 窗的修复逐项移植到 FormOmron 与 FormModbusRtu——①写回网格封送：两窗 SetModbusGridValue 补 IsDisposed/!IsHandleCreated 丢弃+InvokeRequired 时 BeginInvoke 封送(原轮询/写回线程直写 dataGridView1 单元格被 CheckForIllegalCrossThreadCalls=false 掩盖成静默跨线程控件状态累积损坏=配置窗越开越慢头号嫌疑)。②写回长度截断：两窗 xie() 四分支(int/long/float/string) 补 regLen=par.Value[2] TryParse(失败记日志+失败登记+break，解析风格与地址一致)、int/string 取 writeCount=Math.Min(parts.Length,regLen)，long/float 先 valLen=Math.Max(1,regLen/2) 再 Min，超长每相机每通道仅记一条「写回超长截断」日志——溢出值写进相邻通道地址=多相机多寄存器数据互串的直接成因；RTU xie() 四分支同时补网格回写守卫(!gridUi break + xuanzhong_temp<0||!fins_data.ContainsKey continue，防 KeyNotFound 被 per-camera catch 误判写回失败)。③RTU xie_wu() 极速写四分支同款截断(patWriteOk 风格，极速写超长截断日志)，string 分支写入与回显循环同用 writeCount；Omron 无极速写不涉及。④反馈通道绑定唯一性：两窗新增 BindFankui/IsUnboundFankui/_fankuiSyncing 并收敛 8 个 handler(Omron comboBox6/7/9/11/13/15/17/19→c1..c8，RTU cb13..cb20→c1modbusrtu..c8modbusrtu，cb21=c10 chufa 不动)——新值非未绑定态且与旧值不同则查 camera_dic 同通道占用，占用记日志+防重入回退 SelectedIndex+弹窗说明、不写 ini；Load 期对 ini 存量重复绑定仅记日志不弹窗不改配置。⑤连接成功 UI 封送：两窗 button1_Click 成功分支收敛到新助手 SyncConnectedUiState()(IsDisposed/!IsHandleCreated 丢弃+InvokeRequired 时 BeginInvoke)，修 Load 的 Task.Run 池线程直写 button/panel/userControlCurve 跨线程 UI 写；连同 v1.3.16 的 modbustcp 窗共三窗同款。⑥前提作废记档：现场未用 frm3 modbustcp，v1.3.16 中问题2-② frm3 写回上限、问题2-⑤ Form3 lock、问题3 Form3 DataFormat 三项前提不成立，只记档不改码。⑦仍延后：#9 恢复 CheckForIllegalCrossThreadCalls(需全量后台线程控件写审计留单列轮次)、死代码清单(仅记录不删、CloseXieWuSocket 必须保留)、CreateLastRunRecord 异步化/12 处 Task.Run 内联(等现场 PerfReport 数据)。构建 0 error、单测 20/20。",
            "v1.3.16  2026-09-24  第21轮(三问题审计②①落地：多相机数据互串截断+网格越界守卫+跨线程写网格封送+反馈通道绑定唯一性)：①普通写回 xie() 四分支(int/long/float/string) 补通道登记长度截断——regLen 取 par.Value[2]，解析失败记日志+保留 pending+break(同地址解析风格)、<1 夹到1；int/string 每值1寄存器取 writeCount=Math.Min(parts.Length,regLen)，long/float 每值2寄存器先 valLen=Math.Max(1,regLen/2) 再 Min，与极速写 XieWuWriteOne 逐分支语义对齐(原普通路不截断、溢出值写进相邻通道地址=多相机多寄存器数据互串的直接成因)；超长截断时每相机每通道仅记一条日志防刷屏。②四分支网格回写循环补 xuanzhong_temp<0||!fins_data.ContainsKey 守卫——原 KeyNotFound 异常被 per-camera catch 吞掉、会把已成功的 PLC 写误判为「写回单相机异常」并计入 pending TTL 重试；守卫仅跳过 UI 回写不影响已写 PLC 的值。③问题1(配置窗越开越慢)头号嫌疑修复：SetModbusGridValue 原在轮询/写回线程直写 dataGridView1 单元格，被顶层 CheckForIllegalCrossThreadCalls=false(Form1.cs:215，#9 遗留)掩盖成静默的跨线程控件状态累积损坏；改为 IsDisposed/!IsHandleCreated 直接丢弃、InvokeRequired 时 BeginInvoke 封送到 UI 线程(调用方已有 Visible+250ms 节流门控，入队量有界)，#9 恢复跨线程检查留后续轮次。④问题2-④反馈通道绑定唯一性：comboBox6/7/9/11/13/15/17/19 八个 SelectedIndexChanged 收敛到新助手 BindFankui(cam,cb,iniSection)——新值非未绑定态(空/0/无)且与旧值不同时遍历 camera_dic 查同通道占用，占用则记日志+_fankuiSyncing 防重入标志回退 SelectedIndex(DropDownList 下 Text 可能不在 Items，用 IndexOf，-1=清空)+弹窗说明「两相机绑同一通道=同地址互相覆盖」，回退不再写 ini；未冲突才改 camera_dic+落 ini。Load 期对 ini 存量重复绑定仅记日志不弹窗不改配置(载入回填 chushihua=false，handler 天然 no-op 不会误触发)。⑤本轮明确延后(理由记档)：问题2-② frm3 写回上限——混合单/多寄存器布局无法从代码正确界定槽距，先加上限可能误伤正常输出，待现场各通道 changdu 布局核对后再按相邻相机 path+槽距实现；问题2-⑤ Form3 modbus_duxie 的 lock 恢复——HSL 量化册并发行为未确认、且 400ms 超时+日志5s节流可能刷屏，待现场确认后再定；问题3 CDAB/ABCD 字节序不生效——设置本身在配置窗路生效，报告结论即可、本轮不改码，死代码清单(xieWuDataFmt/BuildWriteMultipleRegistersFrame 三重载/SendXieWuFrame)仅记录不删。",
            "v1.3.15  2026-09-24  第20轮(mode4互斥判据收紧为闸门输入级+现场更正)：现场更正第19轮前提有误——mode4 其实是有输出的(前次测试搞错)，第17轮配置窗闸修复后 mode4 已能经配置窗路或 frm3 标准路正常出数；此时第19轮加的串口回退恰好被「配置窗活跃 或 IsEnable 真」关死、在现场休眠无副作用，诊断三件套(切换状态日志/三路首次触发日志/4732 异常日志)保留备用。但复核发现回退互斥判据用了数据存在性(!(IsEnable 且 modbustcp 终端有数据))而非闸门输入本身：在 IsEnable 真、modbustcp 终端空、style 已配的组合下 4732 闸开且会写零值，回退若同时有 serial 数据就与零值互覆双写——判据收紧为 && !frm3.IsEnable：4732 闸开(IsEnable)就不碰，三路互斥完全由两组闸门输入(fins_en&&chushihua、IsEnable)裁决、与数据有无无关，任何状态下必居其一、可证明不双写；代价是 IsEnable 真但 style 未配时不救场(宁可静默不冒双写风险)，该组合由第19轮诊断日志定位。第17/18/19轮其余改动维持不变。",
            "v1.3.14  2026-09-24  第19轮(ModbusTCP输出mode4仍静默—数据路回退+诊断)：第17轮把配置窗闸改成 (outMtcpWin||outMtcp) 后现场 mode4 仍不输出、自动正常；复审证明修复后 mode4 的配置窗路与 frm3 标准路放行集合在任何状态下都不小于自动模式、纯闸门解释不了差异，唯一自洽解释是自动模式真正在写 PLC 的是第三条路—串口分支的寄存器写子路径(Form1.cs 串口分支进入后若 myjob.modbustcp=true 则经 frm3.mdcan.WriteRegister 写寄存器、地址算法与 frm3 标准路完全相同)：自动下 outSerial=true 且现场串口勾选原值 true→它在写；mode4 强制 jobs[i].serial=false 把它关死，而配置窗路因 fins_en/chushihua=false、frm3 标准路因 IsEnable 或 Outputs[modbustcp] 终端无数据或 modbus_style 未配而静默不产出(其 catch 还吞异常无日志)。修复：①serial 快照条件扩为 (outSerial&&serial)||(mode4&&modbustcp)，mode4 下也读出 Outputs[serial]；②串口分支闸加 mode4 回退子句 mode4&&modbustcp&&serial数据非空&&配置窗不活跃&&!(frm3.IsEnable&&modbustcp数据非空)——配置窗能发让配置窗路独发、frm3 标准路能产出让它独发、都不能才借串口子路径发，三路互斥必居其一，进入时 myjob.modbustcp 必真故永远走寄存器写子路径、绝不发原始串口文本，自动/串口/TCP/IO/欧姆龙/RTU/配置窗各模式条件逐字等价改前零回归；③诊断三件套：ApplyOutputMode 每次切换记录三路决策状态(fins_en/chushihua/IsEnable/style/fn/xie/job1串口与modbustcp勾选/两个数据终端存在性)，三条数据路各加切模式后首次触发日志，frm3 标准路原静默 catch 改记异常——现场再测时一行日志即知 mode4 实际走了哪条路、卡在哪一闸。",
            "v1.3.13  2026-09-23  第18轮(显示频率运行时可调)：上屏节拍原是写死的常量 OcxMinIntervalMs=66ms(≈15Hz，R15 为压 CPU 加的封顶)，现场嫌画面顿只能改码重编译；本轮改为界面可调—输出方式下拉右侧新增两个 WinForms 原生控件 labelDisplayHz「显示频率(Hz)」+ numDisplayHz(NumericUpDown，1..100Hz 默认15)，沿用 labelOutputMode/cbOutputMode 同款手法：位置在 Designer 代码里显式指定、不写 resx，设计器可直接拖改。ValueChanged 换算 1000/Hz 回写可变字段 OcxMinIntervalMs(15→66ms 与原常量逐毫秒一致，零回归)并落 ini camera/display_hz，启动处仿 output_mode 的夹取回填(_displayHzSyncing 防回写、键缺失/非法→15Hz)，字段改 volatile(回调/检测线程入队路径读取防御)。生效范围仅 ScheduleOcxPaint 定时器与 KickOcxPaint 收口两处，采集/检测/输出/封程限速(feng) 一律不动：调 1=1000ms 极省 CPU，调 100=10ms 恢复 R15 前流畅度；页内布局已核 y≥350 行 x>237 无占用(tabPage5 宽581、AutoScroll 下滚可见)。",
            "v1.3.12  2026-09-23  第17轮(ModbusTCP输出方式mode4静默修复)：输出方式下拉选「ModbusTCP输出」(mode4) 不输出、选「自动」却正常——getrecord 两条 ModbusTCP 实现互斥闸的判据错位：配置窗路径(Form1.cs:4610) 只认 outMtcpWin(仅 auto/mode6 为 true)、frm3 路径(Form1.cs:4704) 带 !(fins_en&&chushihua) 排除配置窗活跃场景，mode4 下若现场活跃实现是配置窗(fins_en&&chushihua 真) 则两闸同时关死、静默不发；自动模式两闸都开且由 fins_en&&chushihua 二选一、恰好命中活跃那条故能输出。修复：4610 闸改 (outMtcpWin || outMtcp) && fins_en && chushihua，mode4 作为「ModbusTCP总闸」覆盖两条实现，互斥仍由 fins_en&&chushihua 与 4704 的反条件保证必居其一、不双发；mode6 语义不变(与改前等价)，其余 6 路(IO/串口/TCP/欧姆龙/RTU/不输出) 不受影响；改码前临时绕过法：下拉改选「ModbusTCP(配置窗)」(index7)。同轮另一现场问题(多寄存器输出第2寄存器显示 -32768、应为四舍五入后的 0) 读码结论：输出侧无 0x8000/-32768 写入源、frm3/配置窗两路 TryParse 与 int 分支理论值均为 0，疑点集中在 (short)Math.Round(double.Parse) 受 comboBox39 改写的 CurrentCulture 影响、或 FC16 批写前解析抛异常致整批未写(1101 留从站旧值/哨兵)，待现场补通道 fmt/数据格式字节序/frm3 modbus_style+gongnengma/comboBox39 值、或对 1101 单写 0 验证后再修，本轮不改码。",
            "v1.3.11  2026-09-23  第16轮(监控画面4相机排版错位修复)：display() 的 camera_sum>=4 分支(4相机 2×2 排版)硬编码「隐藏启用中的相机3面板、强显相机4/5面板」来凑固定单元格——网格 tableLayoutPanel1 是 3×3 设计单元格 cam1(0,0)/cam2(1,0)/cam3(2,0)/cam4(0,1)/cam5(1,1) 且旧代码从不移动单元格，于是 1~4 启用时 2×2 槽位实际落在 cam1/cam2/cam4/cam5：现场「相机3的画面显示相机4的图、相机4没图(实为相机5的黑面板)、4台都在运行但相机3的图无处显示」；且 tableLayoutPanel5.Visible 被 17 处当作「相机3启用」的代理标志(结果标签路由 case3→c31/c41、NG 详情芯片 c32-c35、双击 c41 开块编辑器)，错误的 false 让相机3的 OK/NG 写进相机4的行、点相机4的标签开的是相机3的工具块，一并随修复归位。新增 ApplyMonitorGrid：按相机号升序把第 k 个启用相机装入第 k 个槽位(行优先，随启用数取 1/2/4/6/9 槽表，各启用数的 ColumnStyles/RowStyles 百分比沿用原分支值不动)，进入先清残留全跨、面板可见性与 myjobN.en 对齐；单相机改为唯一启用面板跨满 3×3(旧固定跨 cam1，仅相机1单独启用时才碰巧正确)；双击最大化的 GetCellPosition 与还原快照(myjob1/2.record)取自当前格位随之自动正确；display() 入口补 camera_sum=0 重算(原靠调用方先清零，重复调用会累加走错排版分支)。cam9 备用面板 tableLayoutPanel18 不动。",
            "v1.3.10  2026-09-23  第15轮(显示管线优化·4相机CPU90+%专项)：①上屏总节拍封顶≈15fps—KickOcxPaint 入口按 _lastOcxKickMs+OcxMinIntervalMs(66ms) 收口，直接投递/续排/定时器三条路径统一限速(旧实现只有定时器路径 8~16ms 有节流、直连路径可绕过)，ScheduleOcxPaint 间隔同步 8~16ms→66ms(用户操作中或单次上屏>30ms 退到 132ms)；4 相机下全分辨率 ToBitmap 约 60~100 次/秒的「分配+整帧转换+Dispose」降到 ≤15 次/秒，采集/检测/输出/feng=0 全部不动(与 VisionMaster 同款「只显示最新帧」语义)；②原图入框前经 DownscaleToBox 等比缩放到 PictureBox 实际尺寸(与渲染模式 Fit 对齐、背景同 60,60,60)：常驻位图十几 MB→几百 KB、后续 WM_PAINT 全走小图，原先 1:1 超出框被裁掉的边缘改为整图可见；③窗体最小化时提前 return 跳过上屏转换(finally 照常复位 jiasu/busy)。",
            "v1.3.9  2026-09-23  第14轮(线程退出+工程卫生)：①Form3 轮询/重连线程 lunxun_monitor、clientmonitor 原 while(true) 无退出标志——进程退出阶段(Form1 已 closing、正在关 socket/冲刷日志)它们仍在发请求、按 checkBox3 自动重连，新增 volatile _exiting + RequestExit()，由 Form1_FormClosing 置位(注意只在真正退出时调用：窗体被隐藏但不销毁的路径 e.Cancel=true 不置位，否则下次打开配置窗轮询已停、功能失效)；②ErrorLog 增日志轮转：Log\\*.txt 按 LastWriteTime 保留 30 天，24h 节流、跑在落盘线程不阻塞调用方、单文件失败只跳过，解决按天分文件只增不减会占满磁盘；③Modbus CRC 算法本体抽到 Core\\ModbusCrc.cs，Tests/UnitTests.csproj 链接同一份源文件让 CRC 回归直连生产代码(原为「逐行复刻 CrcProduction」，复刻只在写下的那一刻与生产一致、之后生产改动它不跟着变)，并更正 GetCRC16 与实现相反的 returns 注释(实际帧尾为 [低,高])；④RunLog 删只写不读的死字段 processCount/iTemp/iTemp1/sumend/sumline/iflag1 与三行无效清零(R10-4 已删其消费端)；⑤.gitignore 目录规则改 audit-*/ 通配(原逐个列举 audit-build/recheck/third，后增的 audit-fix 等目录会漏)。",
            "v1.3.8  2026-09-23  第12+13轮(R12补遗+合理化优化/输出方式总闸)：①输出方式全局互斥—配置窗新增原生 ComboBox cbOutputMode(ini camera/output_mode，-1=自动按原配置=零回退)，ApplyOutputMode 统一改写 myjob1..8 的 IO/串口/TCP/ModbusTCP/配置窗/RTU 开关，getrecord 的 6 个输出分支与 3 个配置窗分支按所选放行、快照只读选中项，运行期选一种即其它全不发(顺带补 myjobN.tcp 无 ini 持久化的缺口)；②同步尾部埋点—_perfTailStart/Ticks/Count 在 getrecord 的 finally 取起点、DetectWorkerLoop 取差值，PerfReport 输出「尾部 X ms」，为判断 CreateLastRunRecord 与 12 处 Task.Run 能否异步化提供依据；③RasterizeRecordToBitmap 在 src 为 Bitmap 时直接交出所有权，去掉每帧一次的整幅位图拷贝；④缺陷统计表 8 段重复逻辑收敛为 UpdateDefectTable 增量更新(存在则原地改计数、否则末尾追加，去掉每帧两次 dataGridView.Visible 开关与 Rows.Clear 全量重建，并剔除初始化残留的空行)；⑤setbox6..13 八处 UI 同步 Invoke 改 BeginInvoke、SetPictureBoxImage 的 Refresh 改 Invalidate；⑥ErrorLog 改入队+后台线程批量落盘(队列封顶2万条、UTF-8无BOM、500ms 批量)，FormClosing/ProcessExit 显式 FlushPending 冲刷，写日志不再持全局锁阻塞相机回调；⑦RunLog 月/日 CSV 增「路径+长度+mtime」读缓存(命中用副本、写后按真实 stat 刷新，不做延迟落盘以保数据完整)，每条记录省两次 O(文件大小) 全量读；⑧serial 的 if 判定移出 Task.Run 外层，与其余 5 路写法对齐。R12补遗：Form3 服务端接入 socket 补 SendTimeout=3000；三通讯窗体 ini 解析失败补日志、小数值统一取整、通道空名/重名兜底(原任一问题都因 Load 的 catch 只记一行日志而静默丢配置)。",
            "v1.3.7  2026-09-23  第11轮修复(第10轮回归+补课)：①跨天/冷启动日文件缺表头回归修复—WriteDate1 新建文件首条数据前补写表头(OpenOrCreate 后原 FileNotFoundException→CreateCsvPath 表头路径不再触发)，WriteDate 跨月同补(并修 v1.3.6 提交说明中'地址读取'未落实部分)；②三通讯窗体 ini 读取族统一加固—bool.Parse(使能)/decimal.Parse(qishi/zongchang)/int.Parse(geshu)/每通道 qishi·changdu 改 TryParse+回退默认+夹取 NUD/循环上界[0,64]·[0,1000](原任一 ini 值手改坏即抛异常，Load 的 catch 只记一行日志并跳过其后 IP/串口/通道配置与自动连接)；int.Parse(小数.ToString()) 改强转+取格越界守卫；③Form3 客户端 socket 补 SendTimeout=3000(发送持 _clientSocketLock，对端不读时持锁时长有界，不再拖住重连/接收收尾)；CloseResources 的 socketClient Close/置空纳入 _clientSocketLock(与 Send/重连全链路串行化，退出不再写无意义 ObjectDisposed 日志)。",
            "v1.3.6  2026-09-23  第10轮修复(独立复核清单)：SubSet JobCount 5/6/7 档位 groupBox 启用修正(原 5 号窗恒禁用且高档位提前打开)；CSV 统计回退防月/日双计(monthCounted)+回退目录改本相机 path/biaotou(原硬编码串目录)，WriteDate1 读取纳入 try+OpenOrCreate+删逐字节扫描死代码(原 try 外抛异常正是双计触发源)；三通讯窗体轮询 Sleep 改 (int) 强转并防 lunxun_time<=0 空转，ini 轮询读取改 TryParse+回退默认+夹取控件范围(原区域小数点/手改小数会 FormatException 杀死轮询线程；地址/通道数读取族遗漏，v1.3.7 补齐)；Form3 三处 socketClient.Send 判空+发送同入 _clientSocketLock(与重连置空串行化)；串口接收空 catch、TCP 合格/不合格发送及连接失败静默 catch 补限流日志(5s 一条)；Form6/Form8 结果标签改循环前清空+逐条追加(原只显示最后一条)、Value 用 ToString 防强转、Form6 补 try；identifier 失败弹窗改记日志；ShowPictureList 删用前 dlg.Dispose(原必抛 ObjectDisposedException)，唯一 Dispose 留设置关闭处；getCode 覆盖二维码前释放旧位图防 GDI 泄漏。轮询线程退出标志与跨线程检查恢复(#5/#9)留单独一轮。",
            "v1.3.5  2026-09-21  第9轮审查修复(加载/相机/ToolBlock 并发)+en 使能收紧：P0—trriger_set 尾段回 UI 线程并加 TryLockAllCameras 超时跳过；bnClose 释放存图缓冲持 bufLock、尺寸仅随真正释放清零；ToolBlock 锁外访问族入 blockLock(gongjukuai/triggerZifu/comboBox38/DataChange 每相机独立 try+入锁，三处 block 替换簇由切换门闩让路+sync_job_meta 入锁)；启动菜单构造收进 UI Invoke(等 IsHandleCreated)。P1—ini→NumericUpDown 赋值前夹取防吞启动；Load 期 Frm2 按门闩定 start 防常驻遮挡；ClassIni FileName 前置赋值(原失败残留 null→静默读写 win.ini)；重连恢复触发模式绕过登录门(sender==null)；重连成功后补探测/下发 GigE 最佳包大小；存 NG 图 case2 删除错位的 myjob1.ng1 门。P2—终结器线程去弹窗；回调注册失败记日志(9处)；CSV 改 Task 局部快照并删 Myjob.tianbiao；display() 相机1 屏蔽补隐藏面板；参数自动下发按 en 收紧(baoguang_set/两处 bnSetParam)。",
            "v1.3.4  2026-09-19  Form3 无协议接收加固：TCP 客户端与服务端连接开启 KeepAlive 并压到 30s 探活(SIO_KEEPALIVE_VALS)，PLC 掉电/网线拔出约 30s 内触发重连（原为系统默认 2 小时）；未匹配触发串时增加粘包/拆包限流诊断日志(含整段内容与长度，正常报文不记)。说明：现场协议是 8 条精确匹配触发串、无分隔符与长度前缀，故不改变解析行为，避免猜协议导致系统性失效。",
            "v1.3.3  2026-09-19  写回 pending TTL 加固：失败计数改按“结果身份”([5]+[4])计数，新帧登记即自动重置(不再继承旧失败计数/旧起始时刻被误丢)；客户端为空与写路径异常也计入失败(原 NRE 被 per-camera catch 吞掉→无限重试+刷日志；TCP 普通写回漏判空一并补齐)；TTL 时间支路改 int 差值；Modbus.cs 读响应等待改差值式超时(原绝对比较跨 TickCount 回绕会死等)。",
            "v1.3.2  2026-09-19  方案切换门闩原子化：xinghao_qiehuan 改 Interlocked.CompareExchange 根除双切换 TOCTOU；Form1 闩读改 Volatile.Read(含回调热路径/自旋等待/断线检测门控)、写改 Volatile.Write；三窗体回执闩改 volatile；cam10 内层分支补 else 复位(原内层不成立时无复位路径)。",
            "v1.3.1  2026-09-19  第二轮审查修复：极速写清 pending 移入锁内并与本值比对、cam9 周期写回加锁且改用反馈通道、方案切换门闩异常也复位、SubSet 工具字典对象修正(7处)、Global\\ 互斥量降级 Local\\、jiasu 兜底复位、blockLock 补漏(Inputs/CreateLastRunRecord)、手参写入入锁(8处)、cbImage 强引用防 GC、写回每相机独立 try、list_block 改并发字典、pending TTL(3次/10秒)、离线单图检测移后台、Form3 显式 GBK 解码。",
            "v1.3.0  2026-09-19  并发与数据一致性修复：blockLock 覆盖 Outputs 读与结果快照、CSV 串帧改锁内快照、普通/极速写回仅成功才清 pending（按 bool 逐次聚合）、RunStatus 空值保护、曲线线程代际校验、RTU 重连加锁与字节序缓存、触发字边沿记忆、Form3 目标字典线程安全、极速写 string 加载期校验；新增「通讯 → 版本」窗口。",
            "v1.2.0  2026-09-14  新增 GitHub Actions CI（单元测试自动构建）。",
            "v1.1.0  2026-09-14  R4 补齐 Omron pending 单事务提交 + 新增单元测试 19 项 + 行尾归一。",
            "v1.0.0  2026-09-13  仓库首个提交：8 相机 Cognex VisionPro 视觉检测（含 P1/P2 审查修复）。09-03~09-05 的通信多实例化与「连接设备」管理器成果已并入此提交（仓库历史压缩，无独立提交）。",
        };

        private static FormVersion _instance;

        /// <summary>
        /// 单例显示：已打开则前置激活，不重复创建（与项目内其它工具窗一致）。
        /// </summary>
        public static void ShowVersion(IWin32Window owner)
        {
            if (_instance == null || _instance.IsDisposed)
                _instance = new FormVersion();
            if (!_instance.Visible)
                _instance.Show(owner);
            _instance.BringToFront();
            _instance.Activate();
        }

        public FormVersion()
        {
            InitializeComponent();

            lblVersion.Text = "当前版本：v" + AppVersion;
            lblReleaseDate.Text = "发布日期：" + AppVersionDate;
            lblRepo.Text = "所属仓库：" + AppRepoName;
            lblTag.Text = "仓库标签：v" + AppVersion + "（git tag，随推送仓库发布）";

            try
            {
                string exePath = Application.ExecutablePath;
                lblBuild.Text = "程序生成时间：" + System.IO.File.GetLastWriteTime(exePath).ToString("yyyy-MM-dd HH:mm:ss");
            }
            catch
            {
                lblBuild.Text = "程序生成时间：-";
            }

            lstTimeline.Items.Clear();
            foreach (string line in VersionTimeline)
                lstTimeline.Items.Add(line);
        }

        private void btnOk_Click(object sender, EventArgs e)
        {
            this.Close();
        }
    }
}
